name: E2E Automation CQA
on:
  workflow_dispatch:
    inputs:
      environment:
        type: string
        description: 'Test env to execute tests. Examples: dev, predevNN, staging, prod'
        required: true
        default: dev
      parallel:
        type: choice
        default: true
        options:
          - true
          - false
      enableRetry:
        type: choice
        default: true
        options:
          - true
          - false
      username:
        type: string
        required: false
  schedule:
    - cron: '45 01 * * 1-5'

env:
  MANUAL_RUN_PROPS:
    '{
      "testEnv" : "${{ github.event.inputs.environment }}",
      "parallel" : "${{ github.event.inputs.parallel }}",
      "enableRetry" : "${{ github.event.inputs.enableRetry }}",
      "allurePrefix" : "cqa-testing/${{ github.event.inputs.environment }}",
      "username" : "${{ github.event.inputs.username }}"
    }'
  CRON_RUN_PROPS:
    '{
      "testEnv" : "dev",
      "parallel" : "true",
      "enableRetry" : "true",
      "allurePrefix" : "cqa-testing/dev"
      "username" :""
    }'

jobs:
  props:
    runs-on: ubuntu-latest
    outputs:
      env_vars: ${{ steps.extract-props.outputs.env_vars }}
    steps:
      - name: Build Extract properties
        id: extract-props
        run: |
          if [ "$GITHUB_EVENT_NAME" = "workflow_dispatch" ]; then
            echo "env_vars=${{ toJson(env.MANUAL_RUN_PROPS) }}" >> $GITHUB_OUTPUT
          else
            echo "env_vars=${{ toJson(env.CRON_RUN_PROPS) }}" >> $GITHUB_OUTPUT
          fi
          echo "$GITHUB_ACTION_REPOSITORY"
          echo "$GITHUB_ACTOR"
          echo "$GITHUB_API_URL"
          echo "$GITHUB_REPOSITORY"
          echo "$GITHUB_RUN_ID"
          echo "${{ github.ref_name }}"
          echo "${{ github.run_id }}"
      - name: Deploy Stage
        uses: fjogeleit/http-request-action@v1
        with:
           url: 'https://ouow563i35aqdho22iz5zilgai.appsync-api.us-east-2.amazonaws.com/graphql'
           method: 'POST'
           # username: ${{ secrets.AWX_USER }}
           # password: ${{ secrets.AWX_PASSWORD }}
           customHeaders: '{"Content-Type": "application/json", "x-api-key": "da2-pus63fgwtrgdrizhsjk2hnuy5a" }'
           data: '{"query":"mutation MyMutation {\n  createCqaDashboard(input: {Branch: \"${{ github.ref_name }}\", PR_Id: \"12345\", PR_title: \"Cqa-qwerty\", User: \"${{ github.actor }}\", action: \"\", approved_by: \"\", approved_time: \"\", created_time: \"${{ github.event.repository.updated_at}}\", environment: \"${{ github.event.inputs.environment }}\", full_suite_parallel2: \"https://cb-qa-reports.s3.amazonaws.com/${{ github.event.inputs.environment }}/${{ github.run_id }}/report2/index.html\", full_suite_parallel1: \"https://cb-qa-reports.s3.amazonaws.com/${{ github.event.inputs.environment }}/${{ github.run_id }}/report1/index.html\", githubrunner_id: \"${{ github.run_id }}\", p1_test_link: \"https://cb-qa-reports.s3.amazonaws.com/${{ github.event.inputs.environment }}/${{ github.run_id }}/index.html\", pending_deployments_git_link: \"${{ github.api_url }}/repos/${{ github.repository }}/actions/runs/${{ github.run_id }}/pending_deployments\", result: \"failure\"})\n {id}}","variables":{}}'
           
  DeployProd:
    name: Deploy to Production
    needs: [props]
    runs-on: ubuntu-latest
    environment: 
      name: testing
      url: 'http://www.myapp.com'
    steps:
      - name: Deploy
        run: echo I am deploying!
